### ISSUE TITLE
box-shadow considered experimental

### ISSUE THREAD

**Issue by jannylund** [racodond/sonar-css-plugin#119]
This plugin still marks box-shadow as an experimental property. However, it seems to be fully supported. 

- https://caniuse.com/#feat=css-boxshadow
- https://www.w3.org/TR/css-backgrounds-3/#box-shadow

Is there some information I'm missing? I also could not find a way to disable this warning since it seems to be below one big rule.

**Comment by racodond** [comment]
Hi @jannylund,

Which version of the CSS plugin are you running?
Because the `box-shadow` property is not tagged as experimental in the latest version (4.18): https://github.com/racodond/sonar-css-plugin/tree/4.18. See https://github.com/racodond/sonar-css-plugin/blob/4.18/css-frontend/src/main/java/org/sonar/css/model/property/standard/BoxShadow.java and https://github.com/racodond/sonar-css-plugin/commit/d013dcde1d421353718c3a87d48bfb8fde46bfa2#diff-7cf873cb70eea6844d4a36ae3e4996f8

Note also that the rule now supports the ability to exclude some properties from being considered as experimental: https://github.com/racodond/sonar-css-plugin/blob/master/css-checks/src/main/java/org/sonar/css/checks/common/ExperimentalPropertyCheck.java#L50

David

**Comment by jannylund** [comment]
@racodond thanks. You are completely right, ~I thought sonar was supporting the update mechanism for this but I'm stuck on 3.1 and SonarQube (LTS) tells me that's the latest available. I'll investigate.~

Nevermind: I seem to have forgotten that I originally installed this manually some year ago. I'll update.

**Comment by racodond** [comment]
Indeed, you have to manually update it. See https://github.com/racodond/sonar-css-plugin/issues/26

**Comment by jannylund** [comment]
@racodond Thanks. I updated manually and all good now.
