### ISSUE TITLE
[curiousity Question] future of sonar-css-plugin

### ISSUE THREAD

**Issue by aepfli** [racodond/sonar-css-plugin#24]
Hi!

I already asked the same question in the sonarqube mailing list, as there was the swap from this project to the one of kalidasya as the main project repo (at least in the sonarqube updatecenter).

Right now it seems like, that this project is improving, and developed further, which is quite nice.

My question is, if the changes made in here, will be back ported to the "main" repo, or at least if it is planned to be done, or not? If not, i am also quite curious about the reasoning.

Anyway i want to thank you again for a great plugin.

Br
Simon

**Comment by racodond** [comment]
Hi Simon,

> I already asked the same question in the sonarqube mailing list, as there was the swap from this project to the one of kalidasya as the main project repo (at least in the sonarqube updatecenter).

OK. I no longer follow the SonarQube mailing. That's why I didn't have the chance to answer or join the discussion.


> Right now it seems like, that this project is improving, and developed further, which is quite nice.

Indeed. I maintain the plugin for my personal needs, for my clients and for whoever raises an issue in the repo.


> My question is, if the changes made in here, will be back ported to the "main" repo, or at least if it is planned to be done, or not? If not, i am also quite curious about the reasoning.

On my side, there's no plan to back port anything to the "main" repo.
I decided to quit the SonarQube community a few months ago because, for numerous reasons, I didn't like how SonarSource was dealing with community work and contributors. I now maintain my plugins (CSS, JSON, Java Properties, Cucumber Gherkin) for my personal needs, for my clients and whoever raises issues in GitHub.

> Anyway i want to thank you again for a great plugin.

Thanks for your kind words!

David
