### ISSUE TITLE
Is this official repo?

### ISSUE THREAD

**Issue by v-karbovnichy** [racodond/sonar-css-plugin#83]
I've just found this repo https://github.com/kalidasya/sonar-css-plugin
It is not a fork, but a pull->change origin->push clone of this repo plus some commits on top already.

Also it contains commit claiming ownership change:
https://github.com/kalidasya/sonar-css-plugin/commit/5891f503a781de39059441d68379e3cf047290e1

Also on plugin library page here: https://docs.sonarqube.org/display/PLUG/Plugin+Library
in "Other Languages" section the link to CSS is going to that repo.

What's happened? On of the repos should explicitly mention in the title what is official and what is not more maintained with a redirect.

Where should I open new issues?

**Comment by kingoleg** [comment]
Let me explain.

Long time https://github.com/racodond/sonar-css-plugin was official css sonar plugin. But once @racodond decided he doesn't want to continue to work with sonar team and even removed github repository.

After that this sonar-css-plugin was created. And that's why it is not a fork.

After, @racodond decide to restore his repo and continue work for it but without official sonar cooperation.

Regarding your last question: I think you should open a new issue in a repo from which your plugin jar os built.

**Comment by v-karbovnichy** [comment]
Oh what a mess :man_facepalming:

**Comment by racodond** [comment]
@v-karbovnichy: All my SonarQube plugins (CSS, JSON, Cucumber Gherkin, ...) are maintained for my personal needs and my customers' needs. They are not official and there are not available in the SonarQube marketplace. Still you can use them. They are released on their respective GitHub release page and on Maven Central.

To answer your question, you can open your issues on my repositories and I'll eventually fix them if they bring added value to the plugin for myself and for my customers.
